### ISSUE TITLE
Support for Material3

### ISSUE THREAD

**Issue by Abhay-cloud** [SnipMeDev/KodeView#18]
![image](https://github.com/SnipMeDev/KodeView/assets/54390973/0ba747d2-8f64-4a15-89ba-ba31cc987a37)
![image](https://github.com/SnipMeDev/KodeView/assets/54390973/171f5223-8043-4ab6-b3a5-6eb26fee8237)

**Comment by tmaxxdd** [comment]
Thanks for suggestion. 

I've created a pending PR for this https://github.com/SnipMeDev/KodeView/pull/19

**Comment by tmaxxdd** [comment]
@Abhay-cloud The PR is closed, and you may try 0.7.0 version

**Comment by Abhay-cloud** [comment]
@tmaxxdd Thanks! I used highlights library, now I can use a newer version of the KodeView.
